### ISSUE TITLE
Design and build chassis for electronics

### ISSUE THREAD

**Issue by SUPScientist** [COAST-Lab/Open-Water-Level#16]
Design and 3D print or mill/route part that slides into PVC housing and serves as chassis for 
- Boron and stacked Adalogger Featherwing
- Battery pack
- Cell antenna

**Comment by gracelower** [comment]
Chassis designs:
[Fabrication/PVC-Enclosure/Enclosure-and-Assembly](https://github.com/COAST-Lab/Open-Water-Level/tree/791c02cdef5b158903b8f5a916721b1455ee3ed0/Fabrication/PVC-Enclosure/Enclosure-and-Assembly)
[Fabrication/Polycase-Enclosure/Enclosure-and-Assembly](https://github.com/COAST-Lab/Open-Water-Level/tree/791c02cdef5b158903b8f5a916721b1455ee3ed0/Fabrication/Polycase-Enclosure/Enclosure-and-Assembly)
