### ISSUE TITLE
Test first issue

### ISSUE THREAD

**Issue by dylan9081** [COAST-Lab/Open-Water-Level#21]
Make sure that this line is NOT commented out:
https://github.com/COAST-Lab/Open-Water-Level/blob/d0d59f2b6c8fb7f4cdda30679c64b3718752d16d/Firmware/SLR_Boron_Maxbotix_MB7092_cm/src/SLR_Boron_Maxbotix_MB7092_cm.ino#L59

**Comment by dylan9081** [comment]
Actually look here instead:
https://github.com/COAST-Lab/Open-Water-Level/blob/d0d59f2b6c8fb7f4cdda30679c64b3718752d16d/Firmware/SLR_Boron_Maxbotix_MB7092_cm/src/SLR_Boron_Maxbotix_MB7092_cm.ino#L47-L58

**Comment by SUPScientist** [comment]
Closing this test issue which was just for demonstration purposes
