### ISSUE TITLE
Fit parts inside in more protected and reliable way

### ISSUE THREAD

**Issue by SUPScientist** [COAST-Lab/Open-Water-Level#32]
In new polycase enclosure, parts are essentially stuffed inside: 
![image](https://github.com/COAST-Lab/Open-Water-Level/assets/7882374/8812b2f9-e4b1-476b-aadc-90d26898cc80)
Find a better way to mount parts inside with, for example, a 3D-printed chassis that holds the electronics and wires in specified locations.

**Comment by SUPScientist** [comment]
@dylan9081, do you want to take a stab at this one?

**Comment by SUPScientist** [comment]
See also https://github.com/COAST-Lab/Open-Water-Level/blob/main/Fabrication/Datasheets/polycase_2d_drawings.pdf for interior dimensions

**Comment by gracelower** [comment]
Chassis designs:
[Fabrication/PVC-Enclosure/Enclosure-and-Assembly](https://github.com/COAST-Lab/Open-Water-Level/tree/791c02cdef5b158903b8f5a916721b1455ee3ed0/Fabrication/PVC-Enclosure/Enclosure-and-Assembly)
[Fabrication/Polycase-Enclosure/Enclosure-and-Assembly](https://github.com/COAST-Lab/Open-Water-Level/tree/791c02cdef5b158903b8f5a916721b1455ee3ed0/Fabrication/Polycase-Enclosure/Enclosure-and-Assembly)
