### ISSUE TITLE
Switch from Serial.print to Log.info

### ISSUE THREAD

**Issue by SUPScientist** [COAST-Lab/Open-Water-Level#33]
### Problem
Firmware currently uses `Serial.print()` type statements frequently. 

### Solution
- According to https://community.particle.io/t/jsn-sr04-callback-confusion/65888/2, it is preferable to use `Log.info()` type statements. However, it's not as simple as just a text-based find and replace operation. 
- Read the docs on logging here: https://docs.particle.io/reference/device-os/api/logging/logging/
- Replace Serial.print-type statements (i.e., including Serial.println, and any formatted print statements) with Log.info type statements.

**Comment by SUPScientist** [comment]
@ gracelower, this would be a great next issue for you to tackle. 

Recommended approach:
- Fork the repo, or if you have a fork, make sure it's caught up with the main repo/branch here.
- Create a branch called something like log_info
- Read the issue as described above and begin wrapping in these changes. Some of the swaps from Serial.print to Log.info will be extremely quick and easy, but some where formatting is needed may present a bit more of a challenge, but I'm confident you're up to it!

**Comment by gracelower** [comment]
@SUPScientist Sounds good - I'll get to this ASAP!

**Comment by gracelower** [comment]
Solution for errors in Line 255:

![Serial print_Log info_Issue](https://github.com/COAST-Lab/Open-Water-Level/assets/170548822/89320eb0-2458-4802-a19a-ac941df2570b)

![Serial print_Log info_PCsolution](https://github.com/COAST-Lab/Open-Water-Level/assets/170548822/64dff093-f12b-4371-b104-cbdf9c94a4fe)

**Comment by gracelower** [comment]
Updated code with Log.info statements and adjusted Getting_Started instructions (in Firmware folder) to reflect these changes [https://github.com/COAST-Lab/Open-Water-Level/commit/c8fbb673e3e3e8fefc8327921a47488ecf37b049](url)

**Comment by gracelower** [comment]
- [x] Find solution to Serial.print issue; document
- [ ] Change sample code in Firmware folder; upload to GH
- [ ] Edit Getting-Started instructions

**Comment by gracelower** [comment]
New proposal: combination of Serial.print + Log.info statements

- Serial.print sends data locally to the serial monitor
- Log.info uses a Particle logging library and is useful for viewing messages in Particle Workbench + remote monitoring
- "If you want to ensure that a message is seen both locally and remotely, use both Serial.print and Log.info for the same message"

A `WORK-IN-PROGRESS` file was created in the Firmware > SLR_Maxbotix_... folder to house code that combines these two statement types. Resulting zeros in the data are only for battery voltage and battery level (due to the device being powered by a computer, not battery).

Please note that part of this proposal was generated in part by AI.

**Comment by SUPScientist** [comment]
Everything sounds like it's on the right trajectory till this last comment that starts "New proposal." Not sure I follow. The goal is to switch completely away from `Serial.print()` type statements and use only `Log.info()` type statements, so I don't think the combo idea is what we want. 

I think the issue is that I disagree with the last bullet of your AI-generated proposal 

> "If you want to ensure that a message is seen both locally and remotely, use both Serial.print and Log.info for the same message"

`Log.info()` will print to screen in my understanding.

**Comment by gracelower** [comment]
I had initially switched all `Serial.print` statements to `Log.info` statements to eliminate all instances of Serial.print as you mentioned. The code compiled and flashed successfully, but I ran into a problem where no results were being returned at all to the serial monitor, instead simply showing the serial monitor opening and closing. When I added some of the `Serial.print` statements back into the code, I was able to see data in the serial monitor once more.

I will do some more research on this and refer back to the Particle Community forum for ways to navigate this issue without reinstating any Serial.print statements. Thanks!

**Comment by gracelower** [comment]
Added `SerialLogHandler logHandler;` to Global objects list before void_setup(void) {

- changed Serial.print statements to Log.info statements
- condensed final two Serial.print statements into single line: `Log.info("Sleeping for %i", seconds_to_sleep);`
- compiled/flashed line-by-line to check results
- updated screenshot of what results should look like in serial monitor & embedded in instructions

![7_BAdaFull](https://github.com/user-attachments/assets/ae34c4c2-f203-4465-99c3-60f46a89acbd)

Changes staged; will commit & submit pull request once current pull request is merged.

**Comment by gracelower** [comment]
Pull request https://github.com/COAST-Lab/Open-Water-Level/pull/45 addresses this issue

**Comment by SUPScientist** [comment]
Agreed. https://github.com/COAST-Lab/Open-Water-Level/pull/45 solves the issue. Closing. Nice work!
